name: CI

on: [push]

jobs:

  ubuntu-ppa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ppa-version:
          # the ppa is currently on 0.7.2 but we need >=0.9
          #- stable
          - unstable
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/${{ matrix.ppa-version }}
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends neovim scdoc lua-busted
    - name: Run the test suite
      run: script -ec "make test BUSTED='busted --filter-out \"^pager mode starts\"'"
      env:
        TERM: dumb

  appimage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appimage-version:
          - v0.9.0
          - nightly
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends scdoc lua-busted
    - name: Download official neovim appimage
      run: |
        wget https://github.com/neovim/neovim/releases/download/${{ matrix.appimage-version }}/nvim.appimage{,.sha256sum}
        sha256sum -c nvim.appimage.sha256sum
        chmod +x nvim.appimage
        ./nvim.appimage --appimage-extract
    - name: Run the test suite
      run: script -ec "make test BUSTED='busted --filter-out \"^parent detection detects\" --filter-out \"^pager mode\"'"
      env:
        TERM: dumb
        NVIMPAGER_NVIM: squashfs-root/usr/bin/nvim

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        brew update
        brew install neovim scdoc luarocks
        luarocks --local install busted
    - name: Run the test suite
      run: script typescript make test BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
      env:
        TERM: dumb

  nix:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v20
    - uses: actions/checkout@v3
    - name: Run the test suite
      run: nix build --print-build-logs
    - name: Update the fake inputs
      run: nix flake update
    - name: Run the test suite again
      run: nix build --print-build-logs
    - name: Run the test suite with nightly neovim
      run: nix build  --print-build-logs '.#nightly'
